export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const LOG_OUT = 'LOG_OUT';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const FETCH_BADGES_REQUEST = 'FETCH_BADGES_REQUEST';
export const FETCH_BADGES_SUCCESS = 'FETCH_BADGES_SUCCESS';
export const FETCH_BADGES_ERROR = 'FETCH_BADGES_ERROR';

export const FETCH_PROMPTS_REQUEST = 'FETCH_PROMPTS_REQUEST';
export const FETCH_PROMPTS_SUCCESS = 'FETCH_PROMPTS_SUCCESS';
export const FETCH_PROMPTS_ERROR = 'FETCH_PROMPTS_ERROR';

export const FETCH_LEVELS_REQUEST = 'FETCH_LEVELS_REQUEST';
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS';
export const FETCH_LEVELS_ERROR = 'FETCH_LEVELS_ERROR';

export const FETCH_LANGUAGES_REQUEST = 'FETCH_LANGUAGES_REQUEST';
export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS';
export const FETCH_LANGUAGES_ERROR = 'FETCH_LANGUAGES_ERROR';

export const FORM_CHANGE = 'FORM_CHANGE';
export const HANDLE_EMAIL_CHANGE = 'HANDLE_EMAIL_CHANGE';
export const HANDLE_NAME_CHANGE = 'HANDLE_NAME_CHANGE';
export const HANDLE_USERNAME_CHANGE = 'HANDLE_USERNAME_CHANGE';
export const HANDLE_LANGUAGE_CHANGE = 'HANDLE_LANGUAGE_CHANGE';
export const HANDLE_LEVEL_CHANGE = 'HANDLE_LEVEL_CHANGE';

export const END_CALL = 'END_CALL';
<<<<<<< HEAD

export const TRANSLATE_TEXT_REQUEST = 'TRANSLATE_TEXT_REQUEST';
export const TRANSLATE_TEXT_SUCCESS = 'TRANSLATE_TEXT_SUCCESS';
export const TRANSLATE_TEXT_ERROR = 'TRANSLATE_TEXT_ERROR';
=======
export const START_CALL = 'START_CALL';
export const RESET_CALL = 'RESET_CALL';
>>>>>>> e7bbb01... Adds tested Redux actions and reducer for starting calls
