export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const FETCH_BADGES_REQUEST = 'FETCH_BADGES_REQUEST';
export const FETCH_BADGES_SUCCESS = 'FETCH_BADGES_SUCCESS';
export const FETCH_BADGES_ERROR = 'FETCH_BADGES_ERROR';

export const FETCH_PROMPTS_REQUEST = 'FETCH_PROMPTS_REQUEST';
export const FETCH_PROMPTS_SUCCESS = 'FETCH_PROMPTS_SUCCESS';
export const FETCH_PROMPTS_ERROR = 'FETCH_PROMPTS_ERROR';

export const FETCH_LEVELS_REQUEST = 'FETCH_LEVELS_REQUEST';
export const FETCH_LEVELS_SUCCESS = 'FETCH_LEVELS_SUCCESS';
export const FETCH_LEVELS_ERROR = 'FETCH_LEVELS_ERROR';

export const FORM_CHANGE = 'FORM_CHANGE';